### ISSUE TITLE
Issue reported on OSX

### ISSUE THREAD

**Issue by TiBeN** [TiBeN/ia-mame#1]
Has been reported on reddit:
https://www.reddit.com/r/MAME/comments/4fruod/iamame_05_mame_thin_wrapper_which_downloads/

version : El Capitan

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/tibennetwork/iamame/IaMame : Unsupported major.minor version 51.0

at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

**Comment by geoffyuen** [comment]
Confirmed not working on my system. I am also using El Capitan. I had to download java 8 from the website as it doesn't come installed on OSX anymore.

**Comment by TiBeN** [comment]
does it works now you have installed java 8 ?

**Comment by geoffyuen** [comment]
Sorry, same error.

**Comment by TiBeN** [comment]
can you type the following on a terminal and copy paste here the output ? 

``` bash
$ java -version
```

**Comment by geoffyuen** [comment]
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

Looks like from the terminal my system still uses 1.6 even though I have 1.8 installed.

**Comment by TiBeN** [comment]
You have the same problem as the original poster on reddit. The problem has been fixed based on the last comment of this thread: http://stackoverflow.com/questions/12757558/installed-java-7-on-mac-os-x-but-terminal-is-still-using-version-6/36061816#36061816

Tell me if the fix works for you

**Comment by geoffyuen** [comment]
Yup that fixed it. Thank you!

Seems like there should be a way to remove 1.6. If I find out a I'll report back here.

**Comment by TiBeN** [comment]
Great ! thank you for report. Now i know it works on Mac too.

**Comment by TiBeN** [comment]
Issue fixed, i close it.
