### ISSUE TITLE
Issue on Ubuntu 15.04

### ISSUE THREAD

**Issue by pcp84** [TiBeN/ia-mame#2]
ia-mame altbeast
Exception in thread "main" java.lang.RuntimeException: Unhandled case: Mame returned no errors while searching for machine altbeast but the machine has not been found on the XML content
    at org.tibennetwork.iamame.mame.MachineRepository.findByName(MachineRepository.java:86)
    at org.tibennetwork.iamame.mame.MameArguments.parseArgs(MameArguments.java:141)
    at org.tibennetwork.iamame.mame.MameArguments.<init>(MameArguments.java:72)
    at org.tibennetwork.iamame.IaMame.main(IaMame.java:53)

**Comment by TiBeN** [comment]
Hi, 
i tried your command (Altered Beast) without problem using mame0170 and ia-mame 0.5 . 
Which Mame version do you use ? Does it works with another game ?

**Comment by pcp84** [comment]
Hi,
I use M.A.M.E. v0.160 and ia-mame 0.5
Nope, in all games I give the same output :(

Glups, I look in a documentation that is only for 0.161+ ?

Update : I install mame 0.173 ( compiling the sources ) and rulz fine !

mame$ ia-mame mslug2
INFO: Download missing rom files: [mslug2, neogeo]
INFO: Machine: Metal Slug 2 - Super Vehicle-001/II (NGM-2410)(NGH-2410)
INFO: Downloading 17064kB / ??kB, progress: ??
INFO: Downloading 1383kB / ??kB, progress: ??
Average speed: 98.78% (26 seconds)

Thanks and sorry :)

**Comment by TiBeN** [comment]
Great ! that's right, only Mame 0.161 + is supported.
Thanks for try and use ia-mame.
I close the issue
