### ISSUE TITLE
Can't download roms when using the "genesis" driver

### ISSUE THREAD

**Issue by nblondiau** [TiBeN/ia-mame#6]
I built the latest version from sources to test the fix for issue #4, an noticed ia-mame won't download roms when using the genesis driver anymore.
It worked fine in version 0.7.

```
$ ia-mame genesis sonic
INFO: Download missing software file: sonic
INFO: Name: Sonic the Hedgehog (Euro, USA)
INFO: Publisher: Sega
INFO: Media interface: megadriv_cart
Exception in thread "main" java.lang.RuntimeException
    at org.tibennetwork.iamame.internetarchive.collectionitem.CollectionItem.downloadFile(CollectionItem.java:141)
    at org.tibennetwork.iamame.internetarchive.collectionitem.MessSoftwareListRoms.download(MessSoftwareListRoms.java:33)
    at org.tibennetwork.iamame.internetarchive.MessAndMameCollection.download(MessAndMameCollection.java:160)
    at org.tibennetwork.iamame.IaMame.downloadFilesIfNeeded(IaMame.java:237)
    at org.tibennetwork.iamame.IaMame.main(IaMame.java:58)
Caused by: java.io.FileNotFoundException: http://archive.org/about/404.php
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(java.base@9-internal/HttpURLConnection.java:1834)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(java.base@9-internal/HttpURLConnection.java:1439)
    at java.net.URL.openStream(java.base@9-internal/URL.java:1112)
    at org.tibennetwork.iamame.internetarchive.collectionitem.CollectionItem.downloadFile(CollectionItem.java:88)
    ... 4 more

```

No problem with the megadriv driver.

```
$ ia-mame megadriv sonic
INFO: Download missing software file: sonic
INFO: Name: Sonic the Hedgehog (Euro, USA)
INFO: Publisher: Sega
INFO: Media interface: megadriv_cart
INFO: Downloading sonic.zip - 377kB / ??kB, progress: 0%
Average speed: 100.00% (2 seconds)
```

**Comment by TiBeN** [comment]
Hi, thanks for testing! 
i just fixed this bug. 
It was a regression introduced by the little refactoring done to implement support of software clones.
